# Generated by Django 4.2.7 on 2024-01-29 20:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDB",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("age", models.IntegerField()),
                ("title", models.CharField(max_length=128)),
                ("join_date", models.DateField(auto_now_add=True)),
                ("active", models.BooleanField()),
            ],
        ),
    ]
