# Generated by Django 4.2.7 on 2023-11-07 10:14

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userAPI", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDB",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("age", models.IntegerField()),
                ("title", models.CharField(max_length=128)),
                ("join_date", models.DateField()),
                ("active", models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
