# Generated by Django 4.2.7 on 2024-02-07 22:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("userAPI", "0003_computerdb"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficeDB",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("num_tables", models.IntegerField()),
                (
                    "user",
                    models.ManyToManyField(related_name="office", to="userAPI.userdb"),
                ),
            ],
        ),
    ]
